### ISSUE TITLE
nom 2.0 tracking issue

### ISSUE THREAD

**Issue by Geal** [Geal/nom#323]
nom 2.0 is happening soon-ish, most of the work is done:
- a compilation feature to deactivate error management and replace it with a simpler, faster version
- there is now a list of traits to implement to get a new input type working with nom. Consequences:
  - all of the `*_s` combinators are now using the byte combinators (there will be less type inference errors now)
  - there's an example arithmetic expression parser using the `BlockBuf` structure from the "bytes" crate
- #34 `ws` combinator to transform a normal parser into a parser for a whitespace separated format
- `do_parse` replacement for `chain` (`chain` is not going away now, probably the following release). The syntax is a bit cleaner, and much simpler (no `mut` nor `?`).
- #40 permutation combinator: successful if all of its child parsers were successful, independently of their order
- `to_result` method for `IResult`
- #169 _breaking change_ the `error` macro is removed, there will be no more conflict with the "log" crate

This is a lot of new features, and there will be some breaking changes, but I want to keep them to a minimum, so I need people to test their current nom parsers with the new code and report any issues.

Code and bugfixes we need to get it ready for a release:
- [x] #325 provide an example (in FAQ or elsewhere) of a parser fo floating point numbers using `digit` and `recognize`. This is something people often struggle with
- [x] #310  Consistent method naming for AsChar
- [x] #140 _breaking change_ use an enum instead of a boolean to indicate endianness
- [x] #217 #226 _breaking change_ basic parsers like `alpha` and `digit` should return `Incomplete` instead of an error on empty inputs
- [x] #252 #285 #307 #313 _breaking change_ make a single, definite version of the end of line parser. Basic token parsing is normally something that should be left to the user, but there are already a few issues and PR for this, and everybody has their own idea, let's fix this once and for all
- [x] _breaking change_ simple error management is now the default (as of 6f36000 ). Verbose error management can be reactivated with the `verbose-errors` compilation feature
- [x] #320 Implement whitespace parsing for do_parse and permutation
- [x] #321 documentation for do_parse, permutation and whitespace parsing
- [x] #322 documentation for simple VS verbose error management
- [x] #301 add `many_till`
- [x] #324 provide an example (in FAQ or elsewhere) or combinator for parsing a separated list of things until the end of data
- [x] #96,#372,#373,#374,#375 cleaner version of length/value and tag/length/value combinators
- [x] #369, #370 fix char indexing for `str` in tag
- [x] #328 remove usages of `chain` from documentation and examples (PR at #341, merge just before release to avoid confusion in the README)
- [x] #329 Document breaking changes and upgrade path

Nice to have (by which I mean I reaaaaally want to get those, but it could get into 2.1):
- [x] #326 provide an example for parsing a simple programming language, now that space separated format are easier to deal with
- [ ] #251 #289 #339 case insensitive tag for &str and &[u8]. Done in 6f6f80f3a008 but the `&str` version does not use proper case folding (cf commit  message)
- [ ] #300 test that `escaped_*` work with `&str`
- [ ] #327 provide an example for parsing indented languages
- [ ] #309 provide an example for a parser tracking line numbers
- [ ] #144 #145 provide an example for an input type that understands the difference between the end of current data and EOF
- [ ] #337 more documentation examples. There's already a lot of code using those, it should be easy to extract and clean it up

**Comment by sjmackenzie** [comment]
@Geal looks great, I can't wait to get started using this, kudos.

**Comment by dtolnay** [comment]
I have been using do_parse! extensively in [`syn`](https://github.com/dtolnay/syn) and it's great. Nicely done.

**Comment by shepmaster** [comment]
> there will be some breaking changes

It would certainly entail more work for you, but having a Cargo feature like `without_features_deprecated_in_v1` would be super useful for those of us that want to start a new parser with new nom. I don't want to use `chain` when the new hotness is `do_parse`. At the very least, some deprecated notation would help prevent me from using items in the "going away" phase.

**Comment by Geal** [comment]
That's a good idea. There's already an effort to remove `chain!` from all the documentation examples. It would be really cool if I could use the deprecation warning in compilation.

**Comment by Geal** [comment]
AAAAAAAND DONE!!!! :)

**Comment by sjmackenzie** [comment]
We're upgrading to `nom` 2.0! https://gitlab.com/dmichiels/fractalide/commit/50b85a4aa111af290aefe3569fecf85b7c8b0582 Thank you @Geal et al!

**Comment by Geal** [comment]
@sjmackenzie that's great!
