### ISSUE TITLE
Tracking issue for 1.0

### ISSUE THREAD

**Issue by Geal** [Geal/nom#82]
nom is getting more stable, and more projects are relying on it, so it's time to break everything again!

Before too many projects use it and we're not able anymore to change the syntax and architecture, a few components should be modified, and some features implemented. Here is a rough list of issues to take care of for the future 1.0 release:
* [x] #18 single character parsers should be available (non-breaking change, implemented before 1.0)
* [x] #33 regular expression parsers
* [x] #69 typed errors
* [x] #81 #101 make `Err` generic over the input type
* [x] #80 new design for `Producer` and `Consumer`
* [x] #83 rename `filter!`
* [x] #107 Provide error macro that doesn't do an early return
* [x] #108 Provide a macro to ignore Incomplete
* [x]  #109 Add a trait to measure input length
* [x] #104 Incomplete in chain requires input implementing `len()`

This release will need a lot of new documentation and tutorials. Here are a few ideas of things that should be written:
* how nom combinators are written, including the macro trick with the input parameter
* how to make a lexing phase by parsing space separated tokens ( #34)
* how to get started on a new format: finding a spec, finding samples, reading the spec, the plumbing to test parsers on multiple files, unit testing for parsers, using `include_bytes!`, how to fuzz with AFL, how to export as a C library
* a FAQ, for the gotchas around parsing stuff with nom, the common errors and well known patterns

**Comment by Rydgel** [comment]
:+1:

**Comment by rseymour** [comment]
I'd love an example parser that for example pulled out ascii strings from a binary stream or something relatively simple but worked as a command line tool.  I'm playing around but the barrier of entry is high w/ a new language, etc.

**Comment by Geal** [comment]
@rseymour a simple version of what you need could be done easily (but not as efficient as `strings` which uses a lot of magic behind the scenes). Read chunks of the stream, then apply something like this:

```rust
fn strings(input:&[u8]) -> IResult<&[u8],Vec<&[u8]>> {
  preceded!(input,      // pass the input to the first combinator,
    opt!(not_ascii),      // in case the file begins with non ascii strings
    many0!(                // loop over the input
      terminated!(       // we match pairs of ascii strings, non ascii part and return the ascii string
        map_res!(is_ascii, str::from_utf8), // if we found an ascii chain, convert it to a string
        opt!(not_ascii)   // in case the file does not end with non ascii strings
      )
    )
}
```

the `is_ascii` and `not_ascii` left as exercise. Also left as exercise, how make a complete ascii string if it spans two chunks :)

**Comment by rseymour** [comment]
I was able to run the code above replacing not_ascii and is_ascii with the digit and alpha public functions.  But when I try to create an is_ascii and not_ascii it bails because those implementations require a lot of internal:: stuff like Position, etc.  Right now just trying to return an Error, but that requires internal::Error as a return type so that won't work in practice.  I hope to get this working just so new rust and nom users can see the intricacies of writing a command line tool that does something.

**Comment by danburkert** [comment]
Is it too late to change the default error type from a `u32` to a Rust enum?  The biggest value I see in this is that an enum can have a custom `Display` impl that prints the exact error message, instead of just the integer value.  I have a feeling that this would require changing a lot of code inside `nom`, but it probably won't break user code too badly, since users rely on the default value a lot of the time.

**Comment by Geal** [comment]
@danburkert this is covered in #69 and I implemented it and merged it in 1.0 in September, so it is not too late :)

Right now, `Error` contains an enum described [here](https://github.com/Geal/nom/blob/master/src/internal.rs#L38-L52).

The type `nom::ErrorKind` is an [enum](https://github.com/Geal/nom/blob/master/src/util.rs#L500-L546) of nom specific error, or `Custom(E)`, with `E` the custom error type.

**Comment by Geal** [comment]
nom 1.0 is now released! There is an [upgrading documentation](https://github.com/Geal/nom/wiki/Upgrading-to-nom-1.0) to help you switch to the new version.

And there's a [release blogpost](https://www.clever-cloud.com/blog/engineering/2015/11/16/nom-1-0/) if you need more info (also, [reddit link](https://www.reddit.com/r/rust/comments/3t10f3/nom_just_reached_10_cleaner_parsers_more_generic/).

Thank you all for using nom!
